### ISSUE TITLE
problem when update to 1.1.2 with platformio

### ISSUE THREAD

**Issue by MDB80** [me-no-dev/ESPAsyncTCP#70]
Hi,
I've a problem when I update ESPAsyncTCP library. Work fine with version 1.1.0 but not with 1.1.1 and 1.1.2. Can you help me?
Thanks anyway for your excellent work.
Best regards,
Max

-------------------------------------------------------------------------------------

Updating ArduinoJson                     @ 5.11.2         [Up-to-date]
Updating ESPAsyncTCP                     @ 1.1.0          [1.1.2]
Uninstalling ESPAsyncTCP @ 1.1.0:       [OK]
Looking for ESPAsyncTCP library in registry
Found: http://platformio.org/lib/show/305/ESPAsyncTCP
LibraryManager: Installing id=305 @ 1.1.2
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
ESPAsyncTCP @ 1.1.2 has been successfully installed!
Updating ESPAsyncWebServer               @ 1.1.0          [Up-to-date]

when compiling...
................
Compiling .pioenvs\esp_wroom_02\lib\ESPAsyncTCP_ID305\AsyncPrinter.o
Compiling .pioenvs\esp_wroom_02\lib\ESPAsyncTCP_ID305\ESPAsyncTCP.o
Compiling .pioenvs\esp_wroom_02\lib\ESPAsyncTCP_ID305\ESPAsyncTCPbuffer.o
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp: In constructor 'AsyncClient::AsyncClient(tcp_pcb*)':
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:78:28: error: invalid conversion from 'long int (*)(void*, tcp_pcb*, pbuf*, long int)' to 'tcp_recv_fn {aka signed char (*)(void*, tcp_pcb*, pbuf*, signed char)}' [-fpermissive]
tcp_recv(_pcb, &_s_recv);
^
In file included from .piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:27:0:
C:\Users\MD\.platformio\packages\framework-arduinoespressif8266\tools\sdk\lwip\include/lwip/tcp.h:318:18: error:   initializing argument 2 of 'void tcp_recv(tcp_pcb*, tcp_recv_fn)' [-fpermissive]
void             tcp_recv    (struct tcp_pcb *pcb, tcp_recv_fn recv) ICACHE_FLASH_ATTR;
^
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:79:28: error: invalid conversion from 'long int (*)(void*, tcp_pcb*, uint16_t) {aka long int (*)(void*, tcp_pcb*, short unsigned int)}' to 'tcp_sent_fn {aka signed char (*)(void*, tcp_pcb*, short unsigned int)}' [-fpermissive]
tcp_sent(_pcb, &_s_sent);
^
In file included from .piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:27:0:
C:\Users\MD\.platformio\packages\framework-arduinoespressif8266\tools\sdk\lwip\include/lwip/tcp.h:319:18: error:   initializing argument 2 of 'void tcp_sent(tcp_pcb*, tcp_sent_fn)' [-fpermissive]
void             tcp_sent    (struct tcp_pcb *pcb, tcp_sent_fn sent)ICACHE_FLASH_ATTR;
^
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:80:28: error: invalid conversion from 'void (*)(void*, long int)' to 'tcp_err_fn {aka void (*)(void*, signed char)}' [-fpermissive]
tcp_err(_pcb, &_s_error);
^
In file included from .piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:27:0:
C:\Users\MD\.platformio\packages\framework-arduinoespressif8266\tools\sdk\lwip\include/lwip/tcp.h:321:18: error:   initializing argument 2 of 'void tcp_err(tcp_pcb*, tcp_err_fn)' [-fpermissive]
void             tcp_err     (struct tcp_pcb *pcb, tcp_err_fn err)ICACHE_FLASH_ATTR;
^
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:81:31: error: invalid conversion from 'long int (*)(void*, tcp_pcb*)' to 'tcp_poll_fn {aka signed char (*)(void*, tcp_pcb*)}' [-fpermissive]
tcp_poll(_pcb, &_s_poll, 1);
^
In file included from .piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:27:0:
C:\Users\MD\.platformio\packages\framework-arduinoespressif8266\tools\sdk\lwip\include/lwip/tcp.h:320:18: error:   initializing argument 2 of 'void tcp_poll(tcp_pcb*, tcp_poll_fn, u8_t)' [-fpermissive]
void             tcp_poll    (struct tcp_pcb *pcb, tcp_poll_fn poll, u8_t interval)ICACHE_FLASH_ATTR;
^
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp: In member function 'bool AsyncClient::connect(IPAddress, uint16_t)':
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:130:25: error: invalid conversion from 'void (*)(void*, long int)' to 'tcp_err_fn {aka void (*)(void*, signed char)}' [-fpermissive]
tcp_err(pcb, &_s_error);
^
In file included from .piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:27:0:
C:\Users\MD\.platformio\packages\framework-arduinoespressif8266\tools\sdk\lwip\include/lwip/tcp.h:321:18: error:   initializing argument 2 of 'void tcp_err(tcp_pcb*, tcp_err_fn)' [-fpermissive]
void             tcp_err     (struct tcp_pcb *pcb, tcp_err_fn err)ICACHE_FLASH_ATTR;
^
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp: In member function 'AsyncClient& AsyncClient::operator=(const AsyncClient&)':
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:168:28: error: invalid conversion from 'long int (*)(void*, tcp_pcb*, pbuf*, long int)' to 'tcp_recv_fn {aka signed char (*)(void*, tcp_pcb*, pbuf*, signed char)}' [-fpermissive]
tcp_recv(_pcb, &_s_recv);
^
In file included from .piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:27:0:
C:\Users\MD\.platformio\packages\framework-arduinoespressif8266\tools\sdk\lwip\include/lwip/tcp.h:318:18: error:   initializing argument 2 of 'void tcp_recv(tcp_pcb*, tcp_recv_fn)' [-fpermissive]
void             tcp_recv    (struct tcp_pcb *pcb, tcp_recv_fn recv) ICACHE_FLASH_ATTR;
^
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:169:28: error: invalid conversion from 'long int (*)(void*, tcp_pcb*, uint16_t) {aka long int (*)(void*, tcp_pcb*, short unsigned int)}' to 'tcp_sent_fn {aka signed char (*)(void*, tcp_pcb*, short unsigned int)}' [-fpermissive]
tcp_sent(_pcb, &_s_sent);
^
In file included from .piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:27:0:
C:\Users\MD\.platformio\packages\framework-arduinoespressif8266\tools\sdk\lwip\include/lwip/tcp.h:319:18: error:   initializing argument 2 of 'void tcp_sent(tcp_pcb*, tcp_sent_fn)' [-fpermissive]
void             tcp_sent    (struct tcp_pcb *pcb, tcp_sent_fn sent)ICACHE_FLASH_ATTR;
^
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:170:28: error: invalid conversion from 'void (*)(void*, long int)' to 'tcp_err_fn {aka void (*)(void*, signed char)}' [-fpermissive]
tcp_err(_pcb, &_s_error);
^
In file included from .piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:27:0:
C:\Users\MD\.platformio\packages\framework-arduinoespressif8266\tools\sdk\lwip\include/lwip/tcp.h:321:18: error:   initializing argument 2 of 'void tcp_err(tcp_pcb*, tcp_err_fn)' [-fpermissive]
void             tcp_err     (struct tcp_pcb *pcb, tcp_err_fn err)ICACHE_FLASH_ATTR;
^
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:171:31: error: invalid conversion from 'long int (*)(void*, tcp_pcb*)' to 'tcp_poll_fn {aka signed char (*)(void*, tcp_pcb*)}' [-fpermissive]
tcp_poll(_pcb, &_s_poll, 1);
^
In file included from .piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:27:0:
C:\Users\MD\.platformio\packages\framework-arduinoespressif8266\tools\sdk\lwip\include/lwip/tcp.h:320:18: error:   initializing argument 2 of 'void tcp_poll(tcp_pcb*, tcp_poll_fn, u8_t)' [-fpermissive]
void             tcp_poll    (struct tcp_pcb *pcb, tcp_poll_fn poll, u8_t interval)ICACHE_FLASH_ATTR;
^
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp: In member function 'long int AsyncClient::_connected(void*, long int)':
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:292:28: error: invalid conversion from 'long int (*)(void*, tcp_pcb*, pbuf*, long int)' to 'tcp_recv_fn {aka signed char (*)(void*, tcp_pcb*, pbuf*, signed char)}' [-fpermissive]
tcp_recv(_pcb, &_s_recv);
^
In file included from .piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:27:0:
C:\Users\MD\.platformio\packages\framework-arduinoespressif8266\tools\sdk\lwip\include/lwip/tcp.h:318:18: error:   initializing argument 2 of 'void tcp_recv(tcp_pcb*, tcp_recv_fn)' [-fpermissive]
void             tcp_recv    (struct tcp_pcb *pcb, tcp_recv_fn recv) ICACHE_FLASH_ATTR;
^
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:293:28: error: invalid conversion from 'long int (*)(void*, tcp_pcb*, uint16_t) {aka long int (*)(void*, tcp_pcb*, short unsigned int)}' to 'tcp_sent_fn {aka signed char (*)(void*, tcp_pcb*, short unsigned int)}' [-fpermissive]
tcp_sent(_pcb, &_s_sent);
^
In file included from .piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:27:0:
C:\Users\MD\.platformio\packages\framework-arduinoespressif8266\tools\sdk\lwip\include/lwip/tcp.h:319:18: error:   initializing argument 2 of 'void tcp_sent(tcp_pcb*, tcp_sent_fn)' [-fpermissive]
void             tcp_sent    (struct tcp_pcb *pcb, tcp_sent_fn sent)ICACHE_FLASH_ATTR;
^
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:294:31: error: invalid conversion from 'long int (*)(void*, tcp_pcb*)' to 'tcp_poll_fn {aka signed char (*)(void*, tcp_pcb*)}' [-fpermissive]
tcp_poll(_pcb, &_s_poll, 1);
^
In file included from .piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:27:0:
C:\Users\MD\.platformio\packages\framework-arduinoespressif8266\tools\sdk\lwip\include/lwip/tcp.h:320:18: error:   initializing argument 2 of 'void tcp_poll(tcp_pcb*, tcp_poll_fn, u8_t)' [-fpermissive]
void             tcp_poll    (struct tcp_pcb *pcb, tcp_poll_fn poll, u8_t interval)ICACHE_FLASH_ATTR;
^
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp: In member function 'void AsyncServer::begin()':
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:848:30: error: invalid conversion from 'long int (*)(void*, tcp_pcb*, long int)' to 'tcp_accept_fn {aka signed char (*)(void*, tcp_pcb*, signed char)}' [-fpermissive]
tcp_accept(_pcb, &_s_accept);
^
In file included from .piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:27:0:
C:\Users\MD\.platformio\packages\framework-arduinoespressif8266\tools\sdk\lwip\include/lwip/tcp.h:317:18: error:   initializing argument 2 of 'void tcp_accept(tcp_pcb*, tcp_accept_fn)' [-fpermissive]
void             tcp_accept  (struct tcp_pcb *pcb, tcp_accept_fn accept) ICACHE_FLASH_ATTR;
^
*** [.pioenvs\esp_wroom_02\lib\ESPAsyncTCP_ID305\ESPAsyncTCP.o] Error 1
============================================== [ERROR] Took 5.17 seconds ==============================================

**Comment by me-no-dev** [comment]
you are using older esp8266 arduino. maybe use staging version?
